services:
  app:
    image: oven/bun:1-alpine
    container_name: go-for-it-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    command: bun run dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    stdin_open: true
    tty: true
